window.SITE_DATA = {
  profile: {
    name: "Haoran Gao",
    shortName: "HG",
    role: "Software Engineer",
    location: "New York, NY",
    summary:
      "I build reliable products with a focus on practical engineering, clean interfaces, and measurable outcomes.",
    details: [
      "Incoming Software Engineer at Bloomberg.",
      "This website is intentionally simple: clear signal, low maintenance.",
      "HINT: Replace these lines with your latest one-liners when you have time.",
    ],
    image: "assets/images/profile_pictures/profile.webp",
    imageAlt: "Haoran Gao profile photo",
    ctaPrimary: {
      label: "View Projects",
      href: "project.html",
    },
    ctaSecondary: {
      label: "See Gallery",
      href: "gallery.html",
    },
    tags: ["Engineering", "Product Thinking", "Data", "Design Awareness"],
  },
  meta: {
    siteUrl: "https://your-domain.com",
    sameAs: [
      "https://www.linkedin.com/in/harrisongao/",
      "https://github.com/HTK-G",
      "https://www.instagram.com/htk_harrison/",
    ],
  },
  highlights: [
    {
      date: "2026",
      title: "Full-time Transition",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet.",
      image: "assets/images/highlights/WangHong.webp",
      imageAlt: "Academic milestone",
    },
    {
      date: "2025",
      title: "Cross-Discipline Growth",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
      image: "assets/images/highlights/horseshoeHandsome.webp",
      imageAlt: "Travel highlight",
    },
    {
      date: "2024",
      title: "Research Collaboration",
      text: "Published work around online trend analysis and election-related public sentiment behavior.",
      image: "assets/images/highlights/meetingSmile.webp",
      imageAlt: "Research team highlight",
    },
    {
      date: "—",
      title: "Bloomberg Terminal",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/bloomberg_terminal.webp",
      imageAlt: "Bloomberg terminal",
    },
    {
      date: "—",
      title: "Bouldering",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/bouldering.webp",
      imageAlt: "Bouldering",
    },
    {
      date: "—",
      title: "Graduation",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/graduated.webp",
      imageAlt: "Graduation",
    },
    {
      date: "—",
      title: "Happy Moment",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/happy.webp",
      imageAlt: "Happy moment",
    },
    {
      date: "—",
      title: "Horse Shoe Bend",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/horseShoeBend.webp",
      imageAlt: "Horse Shoe Bend",
    },
    {
      date: "—",
      title: "NYU Welcome",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/NYUwelcome.webp",
      imageAlt: "NYU welcome",
    },
    {
      date: "—",
      title: "Project Meeting",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/projectMeeting.webp",
      imageAlt: "Project meeting",
    },
    {
      date: "—",
      title: "Sequoia Visit",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/sequoia.webp",
      imageAlt: "Sequoia",
    },
    {
      date: "—",
      title: "New Journey",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/start_new_journey.webp",
      imageAlt: "Start new journey",
    },
    {
      date: "—",
      title: "Internship",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/un_intern.webp",
      imageAlt: "Internship",
    },
    {
      date: "—",
      title: "With NYU Dean",
      text: "Placeholder highlight.",
      image: "assets/images/highlights/with_nyu_dean.webp",
      imageAlt: "With NYU Dean",
    },
  ],
  homeNotes: [
    {
      title: "Engineering Focus",
      text: "I care about maintainability first: clear architecture, readable code, and thoughtful defaults.",
      image: "assets/images/highlights/jump.webp",
      imageAlt: "Grand Canyon memory",
    },
    {
      title: "Creative Practice",
      text: "My visual work helps me think about hierarchy, narrative, and user attention in product design.",
      image: "assets/images/artwork/makingCat.webp",
      imageAlt: "Printmaking process",
    },
    // background image removed (folder deleted); omitted to avoid broken reference
  ],
  journal: [
    {
      date: "2026-05",
      title: "Site Renovation Started",
      text: "Refactored to a data-driven static structure for easier long-term updates.",
    },
    {
      date: "2026-04",
      title: "Performance Audit",
      text: "Identified oversized image payload as the primary loading bottleneck.",
    },
    {
      date: "2026-03",
      title: "Design Direction",
      text: "Selected professional engineering visual style: clean, restrained, and readable.",
    },
    {
      date: "2026-02",
      title: "Placeholder Entry",
      text: "HINT: Keep entries short, one line each. Add 2-3 entries per quarter.",
    },
    {
      date: "2026-01",
      title: "Placeholder Entry",
      text: "Use this panel as your low-effort progress feed.",
    },
  ],
  projects: {
    links: [
      {
        title: "Sentiment Trend Analysis",
        href: "https://www.nyu.edu/about/news-publications/news/2024/october/yard-signs--hats--and-shirts-online-searches-show-division-in-pr.html",
        text: "Published research article on merchandise search behavior and election sentiment.",
        image: "assets/images/projects/yardsign.webp",
        imageAlt: "Yard sign project",
      },
      {
        title: "Debate Topic Search Study",
        href: "https://www.nyu.edu/about/news-publications/news/2024/september/abortion--immigration--and-project-2025-drove-online-topic-searc.html",
        text: "Coverage of topic search shifts during and after a presidential debate.",
        image: "assets/images/projects/topicSearch.webp",
        imageAlt: "Debate topic search project",
      },
      {
        title: "Debate Sentiment Follow-up",
        href: "https://www.nyu.edu/about/news-publications/news/2024/october/test.html",
        text: "HINT: This URL currently appears to be a placeholder and may need replacement.",
        image: "assets/images/projects/trend.webp",
        imageAlt: "Debate sentiment project",
      },
    ],
    featured: [
      {
        title: "Election Analytics Lab",
        text: "Contributed to predictive analytics experiments linking online search trends and election outcomes.",
        image: "assets/images/highlights/meetingSmile.webp",
        imageAlt: "Lab collaboration",
      },
      {
        title: "Data Communication",
        text: "Focused on translating statistical outcomes into clear narratives for broader audiences.",
        image: "assets/images/highlights/WangHong.webp",
        imageAlt: "Data storytelling",
      },
    ],
  },
  gallery: [
    {
      title: "Where Am I?",
      subtitle: "Monotype Printing · 2025",
      text: "Identity and transition explored through layered print texture.",
      image: "assets/images/artwork/WhereAmI.webp",
      imageAlt: "Where Am I artwork",
    },
    {
      title: "The Gate",
      subtitle: "Ink Painting & Digital Art · 2024",
      text: "Cross-cultural visual language combining graffiti influence and Chinese ink tradition.",
      image: "assets/images/artwork/Gate.webp",
      imageAlt: "The Gate artwork",
    },
    {
      title: "CyberPunk 2022",
      subtitle: "Digital Art · 2022",
      text: "Stylized reinterpretation of cyberpunk aesthetics with regional internet culture references.",
      image: "assets/images/artwork/《赛博贵物：狠活行者》.webp",
      imageAlt: "Cyberpunk artwork",
    },
    {
      title: "@pumpkin",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/@pumpkin.webp",
      imageAlt: "@pumpkin",
    },
    {
      title: "Creation",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/creation.webp",
      imageAlt: "Creation",
    },
    {
      title: "No Smoking Please",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/No_Smoking_Please_.webp",
      imageAlt: "No Smoking Please",
    },
    {
      title: "Printmaking",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/printmaking.webp",
      imageAlt: "Printmaking",
    },
    {
      title: "Romantic",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/Romantic.webp",
      imageAlt: "Romantic",
    },
    {
      title: "Sleep了",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/Sleep了.webp",
      imageAlt: "Sleep了",
    },
    {
      title: "Star",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/star.webp",
      imageAlt: "Star",
    },
    {
      title: "Time Traveler",
      subtitle: "Artwork · —",
      text: "Placeholder artwork.",
      image: "assets/images/artwork/timeTraveler.webp",
      imageAlt: "Time Traveler",
    },
  ],
  contacts: [
    {
      href: "https://www.linkedin.com/in/harrisongao/",
      icon: "assets/images/icons/linkedin.png",
      label: "LinkedIn",
    },
    {
      href: "https://github.com/HTK-G",
      icon: "assets/images/icons/github.png",
      label: "GitHub",
    },
    {
      href: "https://www.instagram.com/htk_harrison/",
      icon: "assets/images/icons/ins.png",
      label: "Instagram",
    },
    {
      href: "mailto:hg2655@nyu.edu",
      icon: "assets/images/icons/email.svg",
      label: "Email",
    },
  ],
};
